# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :Release do
    # add actions here: https://docs.fastlane.tools/actions
    gym(
          scheme: "AwesomeRn", #指定项目的scheme名称
          configuration: "Release", # 指定打包方式，Release 或者 Debug
          silent: true, # 隐藏没有必要的信息
          clean: true, # 是否清空以前的编译信息 true：是
          workspace: "AwesomeRn.xcworkspace",
          include_bitcode: false, #项目中的bitcode 设置
          output_directory: "/Users/user/Desktop/iosbuild/eseampre", # 指定输出文件夹
          output_name: "test_ipa.ipa", #输出的ipa名称
          export_xcargs: "-allowProvisioningUpdates", #忽略文件
          export_method: "enterprise",
          export_options: {
              provisioningProfiles: {
                "com.carbonzero.eseampre" => "eseampre_release"
              }
          }
        )
#         pgyer(api_key: "e26dd4e9894e1bc67f69f0edd1b06d8e")
  end
end
