import {ImageRes} from '#/assets/Assets';
import {ImageRes as ImageResSrc} from '@assets';

export const WORKDIC = {
  ShenSuChuLi: {
    icon: ImageRes.icon_appeal,
    title: '申诉处理',
    toUrl: 'appealHandingListPage',
  },
  GongZuoLiShi: {
    icon: ImageRes.job_history,
    title: '工作历史',
    toUrl: 'workHistory',
  },
  QiTaJiHuaGongZuo: {
    icon: ImageRes.icon_plan_other,
    title: '其它计划工作',
    toUrl: 'planOtherReview',
  },
  JianXiu: {icon: ImageRes.icon_fixed, title: '风机定检', toUrl: 'workOrder'},
  PingJia: {
    icon: ImageRes.icon_evaluate,
    title: '评价',
    toUrl: 'evaluateListPage',
  },
  ShenSu: {icon: ImageRes.icon_appeal, title: '申诉', toUrl: 'appealListPage'}, //appealListPage
  FengDianXiaGuanLi: {
    icon: ImageRes.icon_manage_people,
    title: '风光侠管理',
    toUrl: 'windManInfos',
  },
  JieSuanDan: {
    icon: ImageRes.icon_settle,
    title: '结算单',
    toUrl: 'statementPage',
  },
  HuoBan: {icon: ImageRes.partner, title: '伙伴', toUrl: 'workOrder'},
  GuZhang: {
    icon: ImageRes.fault_handling,
    title: '故障处理',
    toUrl: 'faultWorkOrderRecord',
  }, //
  JieDan: {icon: ImageRes.order_receiving, title: '接单', toUrl: 'takeOrders'},
  PaiDan: {
    icon: ImageRes.order_distribute,
    title: '工单派发',
    toUrl: 'orderDistribute',
  },
  System: {
    icon: ImageRes.icon_message,
    title: '系统通知',
    toUrl: 'personInfomationPage',
  }, //
  ZhiNengZhuShou: {
    icon: ImageRes.icon_robot,
    title: '智能助手',
    toUrl: 'robotMessage',
  },
  JiFen: {icon: ImageRes.icon_integral, title: '积分', toUrl: 'integralPage'},
  ShouRu: {icon: ImageRes.icon_income, title: '收入', toUrl: 'revenuePage'},
  GongZuoZhuangTai: {icon: ImageRes.workStatus, title: '工作状态', toUrl: ''},
  Notice: {icon: ImageRes.icon_notice, title: '业务公告', toUrl: ''},
  securityAlarm: {icon: ImageRes.icon_security, title: '安全告警', toUrl: ''}, // 收件箱-安全告警
  GeRenXinXiWeiHu: {
    icon: ImageRes.personInfo,
    title: '个人信息',
    titleTemp: '注册风光侠',
    toUrl: 'personInfomationPage',
  },
  addApps: {icon: ImageResSrc.addApps, title: '添加应用', toUrl: 'addApps'},
  SheBeiTaiZhang: {
    icon: ImageResSrc.equipmentAccount,
    title: '设备台账',
    toUrl: 'stationInfo',
    layoutId: 43,
    menuCode: 'SheBeiTaiZhangApp',
  },
  SheBeiTaiZhangApp: {
    icon: ImageResSrc.equipmentAccount,
    title: '设备台账',
    toUrl: 'stationInfo',
    layoutId: 43,
    menuCode: 'SheBeiTaiZhangApp',
  },
  ChangZhanGuanLi: {
    icon: ImageResSrc.stationManagement,
    title: '场站管理',
    toUrl: 'stationInfo',
    layoutId: 119,
    menuCode: 'ChangZhanGuanLiApp',
  },
  ChangZhanGuanLiApp: {
    icon: ImageResSrc.stationManagement,
    title: '场站管理',
    toUrl: 'stationInfo',
    layoutId: 119,
    menuCode: 'ChangZhanGuanLiApp',
  },
  GuZhangJiLuApp: {
    icon: ImageResSrc.faultRecord,
    title: '故障记录',
    toUrl: 'stationInfo',
    layoutId: 198,
    menuCode: 'GuZhangJiLuApp',
  },
  WorkTicketApp: {
    icon: ImageResSrc.icon_workTicket,
    title: '工作票',
    toUrl: 'stationInfo',
    layoutId: 197,
    menuCode: 'WorkTicketApp',
  },
  CaoZuoPiaoApp: {
    icon: ImageResSrc.icon_operationTicket,
    title: '操作票',
    toUrl: 'stationInfo',
    layoutId: 231,
    menuCode: 'CaoZuoPiaoApp',
  },
  WoDeRenWuApp: {
    icon: ImageResSrc.icon_myTask,
    title: '我的任务',
    toUrl: 'stationInfo',
    layoutId: 203,
    menuCode: 'WoDeRenWuApp',
  },
  taskList: {
    icon: ImageResSrc.icon_myTask,
    title: '我的任务',
    toUrl: 'stationInfo',
    layoutId: 203,
    menuCode: 'WoDeRenWuApp',
  },
  QueXianJiLuApp: {
    icon: ImageResSrc.icon_defect,
    title: '缺陷记录',
    toUrl: 'stationInfo',
    layoutId: 250,
    menuCode: 'QueXianJiLuApp',
  },
  DingJianJiLuApp: {
    icon: ImageResSrc.icon_inspection,
    title: '定检记录',
    toUrl: 'inspectionRecord',
    layoutId: 284,
    menuCode: 'DingJianJiLuApp',
  },
  DingJianBaoGaoApp: {
    icon: ImageResSrc.icon_inspection_report,
    title: '定检报告',
    toUrl: 'stationInfo',
    layoutId: 287,
    menuCode: 'DingJianBaoGaoApp',
  },
  StatusSubmitFormApp: {
    icon: ImageResSrc.icon_statusReport,
    title: '状态提报单',
    toUrl: 'stationInfo',
    layoutId: 314,
    menuCode: 'StatusSubmitFormApp',
  },
  WarningAlarmsApp: {
    icon: ImageResSrc.icon_earlyWarning,
    title: '预警告警记录',
    toUrl: 'stationInfo',
    layoutId: 324,
    menuCode: 'WarningAlarmsApp',
  },
  RegistrationApprovalApp: {
    icon: ImageResSrc.icon_registration_approval,
    title: '相关方登记',
    toUrl: 'stationInfo',
    layoutId: 343,
    menuCode: 'RegistrationApprovalApp',
  },
  LoadTaskApp: {
    icon: ImageResSrc.personInfo,
    title: '负荷侧任务',
    titleTemp: '负荷侧任务',
    toUrl: 'stationInfo',
    layoutId: 430,
    menuCode: 'LoadTaskApp',
  },
  PeriodicalInspectionPrerunApp: {
    icon: ImageResSrc.icon_periodical_inspection_prerun,
    title: '定检预试',
    toUrl: 'inspectionPredict',
    layoutId: 357,
    menuCode: 'PeriodicalInspectionPrerunApp',
  },
  ProjectChangeApp: {
    icon: ImageResSrc.icon_project_change,
    title: '项目变更',
    toUrl: 'stationInfo',
    layoutId: 403,
    menuCode: 'ProjectChangeApp',
  },
  ProjectManageApp: {
    icon: ImageResSrc.icon_project_manage,
    title: '项目管理',
    toUrl: 'stationInfo',
    layoutId: 366,
    menuCode: 'ProjectManageApp',
  },
  PrerunCheckApp: {
    icon: ImageResSrc.icon_prerun_check,
    title: '预试验收',
    toUrl: 'preRunCheck',
    layoutId: 362,
    menuCode: 'PrerunCheckApp',
  },
  /*------------------------------------------------wt start       -------------------------------------------------------*/
  MaterialCodeApply: {
    icon: ImageResSrc.goodsCodeApply,
    title: '物资编码申请',
    toUrl: 'stationInfo',
    layoutId: 472,
    menuCode: 'MaterialCodeApply',
  },
  SuppliesDir: {
    icon: ImageResSrc.goodsCatalog,
    title: '物资目录',
    toUrl: 'stationInfo',
    layoutId: 493,
    menuCode: 'SuppliesDir',
  },
  TransfersOrder: {
    icon: ImageResSrc.transfersOrder,
    title: '调拨单',
    toUrl: 'stationInfo',
    layoutId: 563,
    menuCode: 'TransfersOrder',
  },
  BadThingMaintenance: {
    icon: ImageResSrc.badThingMaintenance,
    title: '坏件维修',
    toUrl: 'stationInfo',
    layoutId: 516,
    menuCode: 'BadThingMaintenance',
  },
  CheckOrder: {
    icon: ImageResSrc.checkOrder,
    title: '检定单',
    toUrl: 'stationInfo',
    layoutId: 587,
    menuCode: 'CheckOrder',
  },
  SafetyTool: {
    icon: ImageResSrc.safetyTool,
    title: '安全工器具',
    toUrl: 'stationInfo',
    layoutId: 595,
    menuCode: 'SafetyTool',
  },
  InventoryList: {
    icon: ImageResSrc.inventoryList,
    title: '盘点单',
    toUrl: 'stationInfo',
    layoutId: 606,
    menuCode: 'InventoryList',
  },
  /*------------------------------------------------物资库存-------------------------------------------------------*/
  WareHouseManagement: {
    icon: ImageResSrc.storeHouse,
    title: '库房管理',
    toUrl: 'stationInfo',
    layoutId: 11911,
    menuCode: 'WareHouseManagement',
  },
  PutInStorage: {
    icon: ImageResSrc.putInStore,
    title: '入库单',
    toUrl: 'stationInfo',
    layoutId: 507,
    menuCode: 'PutInStorage',
  },
  SuppliesStock: {
    icon: ImageResSrc.suppliesStock,
    title: '物资库存',
    toUrl: 'stationInfo',
    layoutId: 584,
    menuCode: 'SuppliesStock',
  },
  OutBoundOrder: {
    icon: ImageResSrc.outBoundOrder,
    title: '出库单',
    toUrl: 'stationInfo',
    layoutId: 611,
    menuCode: 'OutBoundOrder',
  },
  ToolsAndEquipmentApp: {
    icon: ImageResSrc.gongqiju,
    title: '工器具管理',
    toUrl: 'stationInfo',
    layoutId: 11918,
    menuCode: 'ToolsAndEquipmentApp',
  },
  /*------------------------------------------------wt end-------------------------------------------------------*/
  OnSiteInspectionApp: {
    icon: ImageResSrc.icon_onSiteInspection,
    title: '巡检',
    toUrl: 'stationInfo',
    layoutId: 485,
    menuCode: 'OnSiteInspectionApp',
  },
  RegularWorkApp: {
    icon: ImageResSrc.icon_regularWork,
    title: '定期工作',
    toUrl: 'stationInfo',
    layoutId: 503,
    menuCode: 'RegularWorkApp',
  },
  MonthPlanApp: {
    icon: ImageResSrc.icon_monthPlan,
    title: '月度工作计划',
    toUrl: 'stationInfo',
    layoutId: 540,
    menuCode: 'MonthPlanApp',
  },
  TongXunJiLuApp: {
    icon: ImageResSrc.stationComloss,
    title: '场站通讯中断',
    toUrl: 'stationInfo',
    layoutId: 1587,
    menuCode: 'TongXunJiLuApp',
  },
  JkTongXunJiLuApp: {
    icon: ImageResSrc.centralComloss,
    title: '集控通讯中断',
    toUrl: 'stationInfo',
    layoutId: 1593,
    menuCode: 'JkTongXunJiLuApp',
  },
  TemporaryPowerFailureApp: {
    icon: ImageResSrc.icon_linshitingdian,
    title: '临时停电',
    toUrl: 'stationInfo',
    layoutId: 1652,
    menuCode: 'TemporaryPowerFailureApp',
  },
  ConstantValueApp: {
    icon: ImageResSrc.icon_constantvalue,
    title: '定值管理',
    toUrl: 'stationInfo',
    layoutId: 1688,
    menuCode: 'ConstantValueApp',
  },
  ChuNengTaskApp: {
    icon: ImageResSrc.chu_neng_task,
    title: '储能运维管理',
    titleTemp: '储能运维管理',
    toUrl: 'stationInfo',
    layoutId: 1661,
    menuCode: 'ChuNengTaskApp',
  },
  LoadSideStopPower: {
    icon: ImageResSrc.loss_power,
    title: '停电申请',
    titleTemp: '停电申请',
    toUrl: 'stationInfo',
    layoutId: 1711,
    menuCode: 'LoadSideStopPower',
  },
  PersonManageApp: {
    icon: ImageResSrc.third_person,
    title: '运维第三方人员',
    titleTemp: '运维第三方人员',
    toUrl: 'stationInfo',
    layoutId: 1754,
    menuCode: 'PersonManageApp',
  },
  AcceptanceCheckApp: {
    icon: ImageResSrc.acceptanceTask,
    title: '验收尽调',
    titleTemp: '验收尽调',
    toUrl: 'stationInfo',
    layoutId: 1779,
    menuCode: 'AcceptanceCheckApp',
  },
  DeliverManageApp: {
    icon: ImageResSrc.third_person_deliver,
    title: '交付第三方人员',
    titleTemp: '交付第三方人员',
    toUrl: 'stationInfo',
    layoutId: 1791,
    menuCode: 'DeliverManageApp',
  },
};
